"""
playbooks_blueprint.py — Suburban-SOC dynamic HTML playbook system.

Registers /playbooks (dashboard) and /playbooks/<id> (detail view) as a
Flask Blueprint on the existing SOC AI Agent app (agent_app.py), rather than
introducing a separate service or frontend framework. Read-only, display-only
routes: this module never executes, shells out to, or dispatches any
containment action. Commands and queries found in playbook content are
rendered as text with a copy-to-clipboard affordance only — actual
containment execution stays exclusively in the existing approval-queue /
Hive-Mind broker path (scripts/hive-mind-broker/), unaffected by this file.

Data source: playbooks/data/<rule_id>.json, generated by
playbooks/migration/split_ir_sigma_playbook.py from
docs/playbooks/IR_Sigma_Playbook.md. No database is introduced — playbook
data and the registry are flat JSON files read from disk, consistent with
this migration's constraint against adding new infrastructure.
"""
from __future__ import annotations

import json
from pathlib import Path

from flask import Blueprint, render_template, abort, request, jsonify

# scripts/setup/ai_agent/ -> repo root is 3 levels up.
REPO_ROOT = Path(__file__).resolve().parents[3]
DATA_DIR = REPO_ROOT / "playbooks" / "data"
ENUMS_PATH = REPO_ROOT / "playbooks" / "schema" / "enums.json"
TEMPLATE_DIR = Path(__file__).resolve().parent / "templates"

playbooks_bp = Blueprint(
    "playbooks",
    __name__,
    template_folder=str(TEMPLATE_DIR),
)


def _load_enums() -> dict:
    if not ENUMS_PATH.exists():
        return {}
    return json.loads(ENUMS_PATH.read_text(encoding="utf-8"))


def _load_all_playbooks() -> list[dict]:
    """Reads every playbooks/data/*.json. Cheap enough (120 small files) to
    do per-request rather than caching + risking staleness after a
    migration script re-run; revisit if this becomes a hot path."""
    records = []
    if not DATA_DIR.exists():
        return records
    for path in sorted(DATA_DIR.glob("*.json")):
        try:
            records.append(json.loads(path.read_text(encoding="utf-8")))
        except (json.JSONDecodeError, OSError):
            # A malformed record must not take the whole dashboard down.
            continue
    return records


def _load_playbook(rule_id: str) -> dict | None:
    # rule ids are validated to [a-z0-9_]+ by the schema; reject anything
    # else before it ever reaches a filesystem path.
    if not rule_id or not all(c.isalnum() or c == "_" for c in rule_id) or not rule_id.islower():
        return None
    path = DATA_DIR / f"{rule_id}.json"
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return None


def build_registry() -> list[dict]:
    """Central source of truth (build-prompt Phase 13), derived from the
    data files rather than hand-maintained, so registry and content can
    never drift apart."""
    registry = []
    for pb in _load_all_playbooks():
        registry.append({
            "id": pb["id"],
            "title": pb["title"],
            "category": pb.get("category", ""),
            "severity": pb.get("severity", ""),
            "status": pb.get("status", ""),
            "tags": pb.get("tags", []),
            "integrations": pb.get("integrations", []),
        })
    return registry


@playbooks_bp.route("/playbooks", methods=["GET"])
def dashboard():
    registry = build_registry()
    enums = _load_enums()

    q = (request.args.get("q") or "").strip().lower()
    category = request.args.get("category") or ""
    severity = request.args.get("severity") or ""
    integration = request.args.get("integration") or ""

    def matches(entry: dict) -> bool:
        if q and q not in entry["title"].lower() and q not in entry["id"].lower():
            return False
        if category and entry["category"] != category:
            return False
        if severity and entry["severity"] != severity:
            return False
        if integration and integration not in entry["integrations"]:
            return False
        return True

    filtered = [e for e in registry if matches(e)]

    return render_template(
        "playbooks_dashboard.html",
        playbooks=filtered,
        total_count=len(registry),
        filtered_count=len(filtered),
        categories=enums.get("category", []),
        severities=enums.get("severity", []),
        integrations=enums.get("integrations", []),
        query=q,
        selected_category=category,
        selected_severity=severity,
        selected_integration=integration,
    )


@playbooks_bp.route("/playbooks/<rule_id>", methods=["GET"])
def detail(rule_id: str):
    playbook = _load_playbook(rule_id)
    if playbook is None:
        abort(404)
    return render_template("playbooks_detail.html", playbook=playbook)


@playbooks_bp.route("/playbooks/<rule_id>/context.json", methods=["GET"])
def ai_context(rule_id: str):
    """Structured, machine-consumable context for the AI triage layer
    (build-prompt Phase 16) — the AI layer reads this, not the rendered
    HTML. Read-only, no containment fields, no execution."""
    playbook = _load_playbook(rule_id)
    if playbook is None:
        abort(404)
    return jsonify({
        "playbook": playbook["id"],
        "title": playbook["title"],
        "severity": playbook["severity"],
        "category": playbook["category"],
        "mitre": playbook.get("mitre", {}),
        "aiContext": playbook.get("aiContext", {}),
    })


@playbooks_bp.errorhandler(404)
def not_found(_e):
    return render_template("playbooks_404.html"), 404
